using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace StudentRegistration.Models
{
    public class StudentRegistration
    {
        [Required]
        [Display(Name = "Student Name")]
        public string StudentName { get; set; }

        [Display(Name = "Age")]
        [Range(0, 99, ErrorMessage = "Please enter a valid Age")]
        public int StudentAge { get; set; }

        [Display(Name = "Date of Birth")]
        [DataType(DataType.Date)]
        public DateTime DOB { get; set; }

        [Required]
        [Display(Name = "Email Address")]
        [DataType(DataType.EmailAddress)]
        public string EmailAddress { get; set; }

        [Display(Name = "Confirm Email")]
        [Compare("EmailAddress", ErrorMessage = "The email address does not match.")]
        public string ConfirmEmail { get; set; }

        [Display(Name = "Major")]
        public MajorList Major { get; set; }

    }

    public class ExampleClass
    {
        public static int Test(ref int a)
        {
            return a *= a;
        }
    }


    public enum MajorList
    {
        Accounting,
        AccountingTechnician,
        ActuarialScience,
        AdultDevelopment_Aging_Gerontology,
        Advertising,
        Aeronautical_AerospaceEngineeringTechnologies,
        Aerospace_AeronauticalEngineering,
        AfricanAmericanStudies,
        AgribusinessOperations,
        AgriculturalBusiness_Management,
        AgriculturalEconomics,
        AgriculturalEducation,
        AgriculturalMechanization,
        AgriculturalProduction,
        Agricultural_Bioengineering,
        Agriculture__General,
        Agronomy_CropScience,
        AircraftMechanics_Technology,
        AircraftPiloting_Navigation,
        Alcohol_DrugAbuseCounseling,
        AmericanIndian_NativeAmericanStudies,
        American_EnglishLiterature,
        AnimalSciences,
        Anthropology,
        AppliedMathematics,
        ArchitecturalDrafting_CADTechnology,
        ArchitecturalEngineering,
        ArchitecturalEngineeringTechnology,
        ArchitecturalEnvironmentalDesign,
        Architecture__General,
        AreaStudies__General__African__MiddleEastern,
        ArtEducation,
        ArtHistory__Criticism_Conservation,
        Art__General,
        AsianAreaStudies,
        AsianLanguages_Literatures,
        Astronomy,
        AthleticTraining,
        AtmosphericSciences_Meteorology,
        AutobodyRepair_Technology,
        AutomotiveEngineeringTechnology,
        AutomotiveMechanics_Technology,
        Aviation_AirwayScience__General,
        AviationManagement_Operations,
        AvionicsTechnology,
        Banking_FinancialSupportServices,
        Bible_BiblicalStudies,
        Biochemistry_Biophysics,
        Biology__General,
        BiomedicalEngineering,
        BusinessAdministration_Management__General,
        BusinessEducation,
        Business_ManagementQuantitativeMethods__General,
        Business_ManagerialEconomics,
        Career_TechnicalEducation,
        Cell_CellularBiology,
        ChemicalEngineering,
        Chemistry,
        ChildCareServicesManagement,
        ChildDevelopment,
        Chiropractic_Pre_Chiropractic,
        Cinema_Film,
        Cinematography_Film_VideProduction,
        City_Urban_RegionalPlanning,
        CivilEngineering,
        CivilEngineeringTechnology,
        Classical_AncientLanguages_Literatures,
        CommunicationDisorderServices__SpeechPathology,
        CommunicationsTechnology__General,
        Communications__General,
        CommunityOrganization_Advocacy,
        ComparativeLiterature,
        Computer_InformationSciences__General,
        ComputerEngineering,
        ComputerEngineeringTechnology,
        ComputerNetworking_Telecommunications,
        ComputerScience_Programming,
        ComputerSoftware_MediaApplications,
        ComputerSystemAdministration,
        ConstructionEngineering_Management,
        ConstructionTrades__carpentry__plumbing__electrical,
        Construction_BuildingTechnology,
        Consumer_FamilyEconomics,
        Corrections,
        Cosmetology_Hairstyling,
        Counseling_StudentServices,
        CourtReporting,
        CreativeWriting,
        CriminalJustice,
        Criminology,
        CulinaryArts_ChefTraining,
        Curriculum_Instruction,
        Dance,
        DataManagementTechnology,
        DentalAssisting,
        DentalHygiene,
        Dentistry_Pre_Dentistry,
        Design_VisualCommunications__General,
        DieselMechanics_Technology,
        DigitalCommunications_Media,
        Divinity_Ministry,
        Drafting_CADTechnology__General,
        EarlyChildhoodEducation,
        Ecology,
        Economics,
        EducationalAdministration,
        Electrical__Electronics_CommunicationsEngineering,
        Electrical__ElectronicsEngineeringTechnologies,
        Electrical_ElectronicsEquipInstallation_Repair,
        Electromechanical_BiomedicalEngineeringTechnologies,
        ElementaryEducation,
        EmergencyMedicalTechnology,
        Engineering_Pre_Engineering__General,
        EngineeringTechnology__General,
        EnglishLanguage_Literature__General,
        English_as_a_Second_LanguageEducation,
        English_LanguageArtsEducation,
        EnvironmentalControlTechnologies,
        EnvironmentalHealthEngineering,
        EnvironmentalScience,
        Ethnic_MinorityStudies__General,
        EuropeanAreaStudies,
        ExerciseScience_Physiology_Kinesiology,
        Family_ConsumerSciences__General,
        FashionMerchandising,
        Fashion_ApparelDesign,
        Finance__General,
        FinancialPlanning_Services,
        Fine_StudioArts,
        FireProtection_SafetyTechnology,
        Food_Nutrition,
        FoodSciences_Technology,
        ForeignLanguagesEducation,
        ForeignLanguages_Literatures__General,
        Forestry,
        FrenchLanguage_Literature,
        FuneralServices_MortuaryScience,
        Genetics,
        Geography,
        Geological_EarthSciences,
        GermanLanguage_Literature,
        Graphic_PrintingEquipmentOperation,
        GraphicDesign,
        Health_PhysicalEducation_Fitness,
        HealthEducation,
        HealthServicesAdministration__General,
        Health_RelatedProfessions_Services__General,
        Health_MedicalTechnology__General,
        Heating_AirCond_RefrigInstall_Repair,
        History,
        HorticultureOperations_Management,
        HorticultureScience,
        Hospital_FacilitiesAdministration,
        Hotel_MotelManagement,
        HumanResourcesDevelopment_Training,
        HumanResourcesManagement,
        IndustrialDesign,
        IndustrialEngineering,
        IndustrialProductionTechnologies,
        InformationScience,
        Insurance_RiskManagement,
        InteriorArchitecture,
        InteriorDesign,
        InternationalBusinessManagement,
        InternationalRelations_Affairs,
        Investments_Securities,
        Journalism__Broadcast,
        Journalism__Print,
        JuniorHigh_MiddleSchoolEducation,
        Labor_IndustrialRelations,
        LandscapeArchitecture,
        LatinAmericanAreaStudies,
        Latino_ChicanoStudies,
        Law_Pre_Law,
        LawEnforcement,
        LegalAdministrativeAssisting_Secretarial,
        LegalStudies__General,
        LiberalArts_GeneralStudies,
        LibraryScience,
        Linguistics,
        Logistics_MaterialsManagement,
        MachineToolTechnology,
        ManagementInformationSystems,
        Marine_AquaticBiology,
        MarketingManagement_Research,
        MassCommunications,
        MassageTherapy,
        MathematicsEducation,
        Mathematics__General,
        MechanicalDrafting_CADTechnology,
        MechanicalEngineering,
        MechanicalEngineeringTechnology,
        Mechanics_Repairers__General,
        MedicalAssisting,
        MedicalLaboratoryTechnology,
        MedicalOffice_Secretarial,
        MedicalRadiologicTechnology,
        MedicalRecords,
        Medical_ClinicalAssisting__General,
        Medicine_Pre_Medicine,
        MentalHealthCounseling,
        Microbiology_Immunology,
        MiddleEasternLanguages_Literatures,
        MilitaryTechnologies,
        Multi_InterdisciplinaryStudies,
        Multimedia_Animation_SpecialEffects,
        MusicEducation,
        Music__General,
        Music__Performance,
        Music__Theory_Composition,
        NaturalResourcesConservation__General,
        NaturalResourcesManagement,
        NorthAmericanAreaStudies,
        NuclearEngineering,
        NuclearMedicineTechnology,
        Nursing__Practical_Vocational_LPN,
        Nursing__Registered_BS_RN,
        OccupationalTherapy,
        OccupationalTherapyAssisting,
        OfficeSupervision_Management,
        OperationsManagement_Supervision,
        Optometry_Pre_Optometry,
        OrganizationalBehavior,
        OsteopathicMedicine,
        Paralegal_LegalAssistant,
        Parks__Recreation,_Leisure__General,
        Parks_Rec_LeisureFacilitiesManagement,
        PersonalServices__General,
        Pharmacy_Pre_Pharmacy,
        Philosophy,
        Photography,
        PhysicalEducation_Coaching,
        PhysicalSciences__General,
        PhysicalTherapy_Pre_PhysicalTherapy,
        PhysicalTherapyAssisting,
        PhysicianAssisting,
        Physics,
        PoliticalScience_Government,
        PostsecondaryEducation,
        PrecisionProductionTrades__General,
        ProtectiveServices__General,
        Psychiatric_MentalHealthTechnician,
        Psychology__Clinical_Counseling,
        Psychology__General,
        PublicAdministration,
        PublicAdministration_Services__General,
        PublicAffairs_PublicPolicyAnalysis,
        PublicHealth,
        PublicRelations_OrganizationalCommunication,
        PublicSpeaking,
        Purchasing_Procurement_ContractsManagement,
        QualityControl_SafetyTechnologies,
        Radio_TelevisionBroadcasting,
        Radio_TelevisionBroadcastingTechnology,
        RealEstate,
        RehabilitationTherapy,
        Religion,
        ReligiousEducation,
        RespiratoryTherapyTechnology,
        Restaurant_FoodServicesManagement,
        Sales__Merchandising,_Marketing__General,
        ScienceEducation,
        SecondaryEducation,
        SecretarialStudies_OfficeAdministration,
        SmallBusinessManagement_Operations,
        SocialSciences__General,
        SocialStudies_SciencesEducation,
        SocialWork,
        Sociology,
        SpanishLanguage_Literature,
        SpecialEducation,
        Sport_FitnessAdministration_Management,
        Statistics,
        SurgicalTechnology,
        SurveyingTechnology,
        TeacherAssisting_AideEducation,
        TeacherEducation__General,
        TeacherEducation__Subject_Specific,
        Textile_Apparel,
        TheatreArts_Drama,
        Theology__General,
        Therapy_Rehabilitation__General,
        Tourism_TravelMarketing,
        Transportation_MaterialsMoving__air__ground,_marine,
        Travel_TourismManagement,
        UrbanStudies_UrbanAffairs,
        VeterinarianAssisting_Technology,
        VeterinaryMedicine_Pre_Veterinarian,
        VocationalRehabilitationCounseling,
        WebpageDesign,
        WeldingTechnology,
        Wildlife_WildlandsManagement,
        WomensStudies,
        Zoology
    }
}
